project:
  type: website
  output-dir: docs

website:
  title: "Thuy-Tien Bui"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:   
      - default
      - customstyles.scss
    css: styles.css
    include-after-body: _footer.html
    page-layout: full

editor: visual





